### ISSUE TITLE
Question: Is there a way to get node-up/node-down notifications with epmdless?

### ISSUE THREAD

**Issue by matthew-myers-bose** [oltarasenko/epmdless#18]
Hi, is there a way to get node-down (and node-up) notifications with epmdless, similar to regular distributed Erlang and epmd?

**Comment by tsloughter** [comment]
Do you have `monitor_nodes` enabled? https://erlang.org/doc/man/net_kernel.html#monitor_nodes-1

**Comment by matthew-myers-bose** [comment]
> 
> Do you have `monitor_nodes` enabled? 

Yes, in my test code, I call `:net_kernel.monitor_nodes true`

With regular Node and epmd I had: `Node.connect(node)`
And I have `handle_info` for `:nodeup` and `:nodedown` that are working.

Now, I am just plugging in epmdless, for Node.connect.
`:epmdless_dist.add_node(node, 17013)`

I can see that the nodes are connected, but when I close iex for the other node, I don't get a `:nodedown` message

```elixir
iex(b@127.0.0.1)2> :epmdless_dist.list_nodes
[{{'a', {127, 0, 0, 1}}, {'127.0.0.1', 17013}}]
```

btw, thanks for the quick reply.

**Comment by tsloughter** [comment]
Ok, so it isn't actually able to connect to `a`.

**Comment by matthew-myers-bose** [comment]
Solved. I was missing the `-proto_dist epmdless_proto` part of the `erl` options when starting iex.
Thanks @tsloughter for your help.
