### ISSUE TITLE
use with -remsh

### ISSUE THREAD

**Issue by tsloughter** [oltarasenko/epmdless#2]
As far as I can tell there is no way to use `-remsh` with just `epmdless` (maybe your node discovery project allows `-remsh` to work?).

If this is the case, have you thought about how it might be done? 

Best I can come up with is an optional fallback for port lookup, so in `port_please` if the lookup returns `noport` it'll return a os variable or application env variable value if one is configured and try to connect over that.

Happy to send a PR if you think that is an acceptable solution, or to work on another solution you might have.

**Comment by oltarasenko** [comment]
Hi @tsloughter !

Sorry I did not notice the issue you have created earlier. Could you please check if the following https://github.com/oltarasenko/epmdless/pull/3 idea will work for your case?

**Comment by oltarasenko** [comment]
Thanks. I have merged the proposed solution!
